resources:
- name: gdp-pipeline
  type: git
  source:
    uri: http://github.com/benbrown-x/gdp-pipeline.git
    branch: master

- name: genivi-demo
  type: git
  source:
    uri: http://git.projects.genivi.org/genivi-demo-platform.git
    branch: qemux86-64

- name: artefacts
  type: s3
  source:
    bucket: {{artefacts-bucket}}
    region_name: {{artefacts-region}}
    regexp: demo-artefacts-(.*).tar
    access_key_id: {{artefacts-access-key}}
    secret_access_key: {{artefacts-secret-key}}

jobs:
- name: yocto-demo
  plan:
  - aggregate:
    - get: gdp-pipeline
    - get: genivi-demo
      params: {submodules: all}
  - task: build
    file: gdp-pipeline/yocto/demo.yml
  - put: artefacts
    params: {from: build-output/demo-artefacts-(.*).tgz}
