resources:
- name: git-repo
  type: git
  source:
    uri: git://git.baserock.org/delta/git.git
    branch: master
- name: contest
  type: git
  source:
    uri: ssh://git@git.codethink.co.uk/people/benbrown/concourse.git
    branch: master
    private_key: {{test_key}}

jobs:
- name: build-git
  plan:
  - get: contest
  - task: do-the-thing
    file: contest/build.yml
