resources:
- name: git-repo
  type: git
  source:
    uri: git://git.baserock.org/delta/git.git
    branch: master

jobs:
- name: build-git
  plan:
  - get: git-repo
    trigger: true
  - task: do-the-thing
    privileged: true
    config:
      platform: linux
      image: "docker:///ubuntu"
      run:
        path: sh
        args:
          - -c
          - sudo apt-get -y install make && pwd && ls -a
