resources:
- name: git-repo
  type: git
  source:
    uri: git://git.baserock.org/delta/git.git
    branch: master
- name: contest
  type: git
  source:
    uri: ssh://git@git.codethink.co.uk/people/benbrown/concourse.git
    branch: master
    private_key: {{test_key}}

- name: genivi-demo
  type: git
  source:
    uri: http://git.projects.genivi.org/genivi-demo-platform.git
    branch: qemux86-64

- name: bitbake
  type: git
  source:
    uri: git://git.openembedded.org/bitbake
    branch: 1.26.0

jobs:
- name: build-git
  plan:
  - get: contest
  - task: do-the-thing
    file: contest/build.yml

- name: yocto-demo
  plan:
  - aggregate:
    - get: contest
    - get: genivi-demo
      params: {submodules: all}
    - get: bitbake
  - task: build
    file: contest/yocto/demo.yml
