resources:
- name: git-repo
  type: git
    source:
      uri: git://git.baserock.org/delta/git.git
      branch: master

jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image: "docker:///ubuntu"
      run:
        path: echo
        args: ["Hello, world!"]
  - task: pwd
    config:
      platform: linux
      image: "docker:///ubuntu"
      run:
        path: pwd
  - task: build-git
    config:
      platform: linux
      image: "docker:///ubuntu"
      run:
        path: pwd
